spring:
  application:
    name: spring-ai-workflow # 应用名称
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:7b
        options:
          temperature: 0.2
server:
  port: 8080