spring:
  application:
    name: spring-ai-evaluation # 设置 Spring 应用的名称为spring-ai-evaluation
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:7b
    openai:
      api-key: # 替换成openai的或者阿里百炼的
      chat:
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        completions-path: /v1/chat/completions
        options:
          model: qwen-plus-2025-07-14

server:
  port: 8080