spring:
  application:
    name: spring-ai-chat-ollama
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:8b
        options:
          temperature: 0.5
  profiles:
    active: ollama
server:
  port: 8081
